FROM cgr.dev/chainguard/python:latest-dev AS dev

WORKDIR /app
ENV PATH="/app/venv/bin:$PATH"

COPY target/wheels/ockam-0.1.0-cp311-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl /ockam-0.1.0-cp311-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl
RUN python -m venv /app/venv && pip install /ockam-0.1.0-cp311-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl
