/**
 * @file  error.h
 * @brief Ockam common error defines
 */

#ifndef OCKAM_ERROR_H_
#define OCKAM_ERROR_H_

#include <stdint.h>

#define OCKAM_ERROR_INTERFACE_MASK  0xFF000000
#define OCKAM_ERROR_INTERFACE_SHIFT 24u

typedef uint32_t ockam_error_t;

#define OCKAM_ERROR_NONE 0u

#define OCKAM_ERROR_INTERFACE_MEMORY       (1u << OCKAM_ERROR_INTERFACE_SHIFT)
#define OCKAM_ERROR_INTERFACE_LOG          (2u << OCKAM_ERROR_INTERFACE_SHIFT)
#define OCKAM_ERROR_INTERFACE_VAULT        (3u << OCKAM_ERROR_INTERFACE_SHIFT)
#define OCKAM_ERROR_INTERFACE_TRANSPORT    (4u << OCKAM_ERROR_INTERFACE_SHIFT)
#define OCKAM_ERROR_INTERFACE_KEYAGREEMENT (5u << OCKAM_ERROR_INTERFACE_SHIFT)
#define OCKAM_ERROR_INTERFACE_RANDOM       (6u << OCKAM_ERROR_INTERFACE_SHIFT)
#define OCKAM_ERROR_INTERFACE_IO           (7u << OCKAM_ERROR_INTERFACE_SHIFT)
#define OCKAM_ERROR_INTERFACE_CHANNEL      (8u << OCKAM_ERROR_INTERFACE_SHIFT)
#define OCKAM_ERROR_INTERFACE_ROUTER       (9u << OCKAM_ERROR_INTERFACE_SHIFT)
#define OCKAM_ERROR_INTERFACE_CODEC        (10u << OCKAM_ERROR_INTERFACE_SHIFT)
#define OCKAM_ERROR_INTERFACE_QUEUE        (11u << OCKAM_ERROR_INTERFACE_SHIFT)

#endif
