[package]
name = "low_latency_portal"
version = "0.1.0"
authors = ["Ockam Developers"]
edition = "2021"
license = "Apache-2.0"
publish = false
rust-version = "1.70.0"

[dependencies]
async-trait = "0.1"
hex = "0.4.3"
log = "0.4.22"
ockam = { path = "../../../implementations/rust/ockam/ockam", features = ["aws-lc"] }
serde = { version = "1.0.215", features = ["derive"] }
serde_json = "1.0"
