#!/usr/bin/env bash

set -eo pipefail
[ "$TRACE" ] && set -x

if [ ! -n "$1" ]
then
  echo "Usage: ./build MACOS_INSTALLER_PATH"
  exit 1
fi

macos_installer_path="$1"
if [ ! -d "$macos_installer_path" ]
then
  echo "macOS installer must be present at: $macos_installer_path"
  exit 1
fi

if [ ! -f "_xcode_installer/Xcode_11_Beta_7.xip" ]
then
  echo "Xcode installer must be present at: _xcode_installer/Xcode_11_Beta_7.xip"
  exit 1
fi

# Ensure the build output directory exists
mkdir -p _build

# Use macinbox to create an intermediate box called _ockam_macinbox
# https://github.com/bacongravy/macinbox
sudo macinbox \
  --box-format virtualbox \
  --name _ockam_macinbox \
  --memory 8192 \
  --cpu 4 \
  --no-auto-login \
  --no-gui \
  --installer "$macos_installer_path"

# Create a VM using the intermediate box and provision Xcode etc.
vagrant up
vagrant ssh -c "sw_vers -productVersion" | tr -d '\r' > _build/productVersion
vagrant ssh -c "sw_vers -buildVersion" | tr -d '\r' > _build/buildVersion

# Package the VM as our final builder
box_path="_build/$(cat _build/productVersion)-$(cat _build/buildVersion).virtualbox.box"
vagrant package --output "$box_path"
shasum -a 256 "$box_path" | cut -d' ' -f1 | xargs echo -n > "$box_path.SHA-256"

# Remove the intermediate box
vagrant box remove --force _ockam_macinbox

echo "$box_path"
cat "$box_path.SHA-256"
