Vagrant.configure("2") do |config|
  config.vm.box = "_ockam_macinbox"
  config.vm.boot_timeout = 10000

  # https://github.com/bacongravy/macinbox/issues/37
  config.vm.synced_folder "_xcode_installer", "/xcode_installer", type: :rsync, rsync__chown: false

  # create the vagrant group
  config.vm.provision "shell", privileged: true, inline: <<-SCRIPT
    VAGRANT_GID=$(id -u vagrant)
    dscl . -create /Groups/vagrant
    dscl . -create /Groups/vagrant PrimaryGroupID $VAGRANT_GID
    dscl . -create /Users/vagrant PrimaryGroupID $VAGRANT_GID
  SCRIPT

  # install xcode command line tools
  config.vm.provision "shell", privileged: true, inline: <<-SCRIPT
    touch /tmp/.com.apple.dt.CommandLineTools.installondemand.in-progress;
    PROD=$(softwareupdate -l |
      grep "\*.*Command Line" |
      head -n 1 | awk -F"*" '{print $2}' |
      sed -e 's/^ *//' |
      tr -d '\n')
    softwareupdate -i "$PROD"
  SCRIPT

  # install xcode
  config.vm.provision "shell", privileged: true, inline: <<-SCRIPT
    xip -x /xcode_installer/Xcode_11_GM_Seed.xip
    mv Xcode.app /Applications/
    xcode-select --switch /Applications/Xcode.app/Contents/Developer
    xcodebuild -license accept
    xcodebuild -runFirstLaunch
    rm -rf /xcode_installer
  SCRIPT

  # https://www.apple.com/certificateauthority
  config.vm.provision "shell", privileged: true, inline: <<-SCRIPT
    curl -OL https://developer.apple.com/certificationauthority/AppleWWDRCA.cer
    echo "ce057691d730f89ca25e916f7335f4c8a15713dcd273a658c024023f8eb809c2  AppleWWDRCA.cer" | shasum -a 256 -c -
    security add-trusted-cert -d -r trustRoot -k /Library/Keychains/System.keychain ./AppleWWDRCA.cer
  SCRIPT

  # install homebrew, asdf & xcodegen
  config.vm.provision "shell", privileged: false, inline: <<-SCRIPT
    sudo mkdir -p /usr/local
    CI=1 /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
    brew install coreutils automake autoconf openssl libyaml readline libxslt libtool unixodbc unzip curl
    brew install asdf xcodegen
    echo -e "\n. $(brew --prefix asdf)/asdf.sh" >> ~/.bash_profile
    echo -e "\n. $(brew --prefix asdf)/etc/bash_completion.d/asdf.bash" >> ~/.bash_profile
  SCRIPT

end
