git log ockam_v0.4.2..HEAD implementations/rust/ockam/ockam >ockam-change.log
git log ockam_channel_v0.1.0..HEAD implementations/rust/ockam/ockam_channel >ockam_channel-change.log
git log ockam_core_v0.7.0..HEAD implementations/rust/ockam/ockam_core >ockam_core-change.log
git log ockam_ffi_v0.1.0..HEAD implementations/rust/ockam/ockam_ffi >ockam_ffi-change.log
git log ockam_key_exchange_core_v0.1.1..HEAD implementations/rust/ockam/ockam_key_exchange_core >ockam_key_exchange_core-change.log
git log ockam_key_exchange_x3dh_v0.1.1..HEAD implementations/rust/ockam/ockam_key_exchange_x3dh >ockam_key_exchange_x3dh-change.log
git log ockam_key_exchange_xx_v0.1.1..HEAD implementations/rust/ockam/ockam_key_exchange_xx >ockam_key_exchange_xx-change.log
git log ockam_node_v0.5.0..HEAD implementations/rust/ockam/ockam_node >ockam_node-change.log
git log ockam_node_attribute_v0.1.4..HEAD implementations/rust/ockam/ockam_node_attribute >ockam_node_attribute-change.log
git log ockam_transport_tcp_v0.2.0..HEAD implementations/rust/ockam/ockam_transport_tcp >ockam_transport_tcp-change.log
git log ockam_vault_v0.3.2..HEAD implementations/rust/ockam/ockam_vault >ockam_vault-change.log
git log ockam_vault_core_v0.3.2..HEAD implementations/rust/ockam/ockam_vault_core >ockam_vault_core-change.log
