[bans]
multiple-versions = "deny"
# Dependencies cannot be specified with the "*" version.
wildcards = "deny"

[licenses]
confidence-threshold = 0.95
allow = [
  "Apache-2.0",
  "MIT",
  "BSD-3-Clause",
  "BSD-2-Clause",
  "0BSD",
  "ISC",
  "BlueOak-1.0.0",
  "BSL-1.0",
  "Zlib",
  "Unicode-3.0"
]
exceptions = [
  { allow = ["Apache-2.0 WITH LLVM-exception"], name = "wast", version = "*" },
  { allow = ["Apache-2.0 WITH LLVM-exception"], name = "wasm-encoder", version = "*" },
  { allow = ["OpenSSL"], name = "aws-lc-sys", version = "*" },
  # used by ockam_app_lib only as a build dependency
  { allow = ["MPL-2.0"], name = "cbindgen", version = "*" },
  # used by ockam_command, for the `notify` crate
  { allow = ["CC0-1.0"], name = "notify", version = "*" },
]

[[licenses.clarify]]
name = "webpki"
expression = "ISC"
license-files = [
  { path = "LICENSE", hash = 0x001c7e6c },
]

[[licenses.clarify]]
name = "rustls-webpki"
expression = "ISC"
license-files = [
  { path = "LICENSE", hash = 0x001c7e6c },
]

[advisories]
yanked = "warn"
ignore = [
  # `serde_cbor` is unmaintained
  # (https://rustsec.org/advisories/RUSTSEC-2021-0127.html)
  #
  # Pulled-in by `cddl-cat` which is used for validating
  # CDDL schema conformance in tests.
  "RUSTSEC-2021-0127",
  #
  # yaml-rust is unmaintained. Switching to maintained fork yaml-rust2 is tricky
  # Tracked here https://github.com/build-trust/ockam/issues/7807
  "RUSTSEC-2024-0320",
  # `paste` is unmainted
  # it's  pulled in by `aws-lc`, `kafka-protocol`, `binary-layout`, `stm32h7xx-hal` and `atsamd-hal`
  "RUSTSEC-2024-0436",
  #
  # `atomic-polyfill` is unmaintained
  # it's  pulled in by `heapless`, via `aead v0.5.2`, `aes-gcm v0.10.3`, and `ockam_vault`.
  # This will be solved when `aead v0.6.0` is released.
  "RUSTSEC-2023-0089",
]
# Users who require or prefer Git to use SSH cloning instead of HTTPS,
# such as implemented via "insteadOf" rules in Git config, can still
# successfully fetch advisories with this enabled.
#
# See also:
# https://doc.rust-lang.org/cargo/reference/config.html#netgit-fetch-with-cli
# https://embarkstudios.github.io/cargo-deny/checks/advisories/cfg.html#the-git-fetch-with-cli-field-optional
# https://github.com/EmbarkStudios/cargo-deny/pull/420
git-fetch-with-cli = true
