USE ROLE ACCOUNTADMIN;

--Create Role
CREATE ROLE IF NOT EXISTS MSSQL_API_ROLE;
GRANT ROLE MSSQL_API_ROLE TO ROLE ACCOUNTADMIN;

--Create Database
CREATE DATABASE IF NOT EXISTS MSSQL_API_DB;
GRANT OWNERSHIP ON DATABASE MSSQL_API_DB TO ROLE MSSQL_API_ROLE COPY CURRENT GRANTS;

USE DATABASE MSSQL_API_DB;

--Create Warehouse
CREATE OR REPLACE WAREHOUSE MSSQL_API_WH WITH WAREHOUSE_SIZE='X-SMALL';
GRANT USAGE ON WAREHOUSE MSSQL_API_WH TO ROLE MSSQL_API_ROLE;

--Create compute pool
CREATE COMPUTE POOL IF NOT EXISTS MSSQL_API_CP
  MIN_NODES = 1
  MAX_NODES = 5
  INSTANCE_FAMILY = CPU_X64_XS;

GRANT USAGE ON COMPUTE POOL MSSQL_API_CP TO ROLE MSSQL_API_ROLE;
GRANT MONITOR ON COMPUTE POOL MSSQL_API_CP TO ROLE MSSQL_API_ROLE;

--Create schema
CREATE SCHEMA IF NOT EXISTS MSSQL_API_SCHEMA;
GRANT ALL PRIVILEGES ON SCHEMA MSSQL_API_SCHEMA TO ROLE MSSQL_API_ROLE;

USE SCHEMA MSSQL_API_SCHEMA;

--Create Image Repository
CREATE IMAGE REPOSITORY IF NOT EXISTS MSSQL_API_REPOSITORY;
GRANT READ ON IMAGE REPOSITORY MSSQL_API_REPOSITORY TO ROLE MSSQL_API_ROLE;
