#!/bin/sh -eux

path="$1"
url="$2"
sha256="$3"

_verify_download() {
  local hash="$1"
  echo "${hash} ${hash}.download" | sha256sum -c -
}

curl --silent --show-error --location --compressed --output "${sha256}.download" "$url"

if ! _verify_download "$sha256"; then
  echo "Downloaded file does not match expected checksum!"
  echo ""
  echo "  expected: ${sha256}"
  echo "  actual:   $(sha256sum "${sha256}.download" | cut -d' ' -f1)"
  echo ""

  exit 1
fi


file=$(basename "$url")
case "$file" in
  *.tar.*) mkdir -p "$path"
           tar -xf "$sha256.download" -C "$path" --strip-components=1
           rm "$sha256.download"
           ;;
    *.zip) temp=$(mktemp -d)
           unzip -q -d "$temp" "$sha256.download"
           mkdir -p "$path"
           mv "$temp"/*/* "$path" # "$temp"/*/* has the same effect as tar's --strip-components=1
           rm -rf "$temp"
           rm "$sha256.download"
           ;;
        *) mv "$sha256.download" "$path"
           ;;
esac
