USE ROLE ACCOUNTADMIN;
CREATE ROLE IF NOT EXISTS ockam;

GRANT ROLE ockam TO ROLE ACCOUNTADMIN;
GRANT CREATE INTEGRATION ON ACCOUNT TO ROLE ockam;
GRANT CREATE COMPUTE POOL ON ACCOUNT TO ROLE ockam;
GRANT CREATE WAREHOUSE ON ACCOUNT TO ROLE ockam;
GRANT CREATE DATABASE ON ACCOUNT TO ROLE ockam;
GRANT CREATE APPLICATION PACKAGE ON ACCOUNT TO ROLE ockam;
GRANT CREATE APPLICATION ON ACCOUNT TO ROLE ockam;

GRANT BIND SERVICE ENDPOINT ON ACCOUNT TO ROLE ockam;

CREATE WAREHOUSE IF NOT EXISTS ockam_warehouse WITH WAREHOUSE_SIZE='XSMALL';
GRANT ALL ON WAREHOUSE ockam_warehouse TO ROLE ockam;

CREATE DATABASE IF NOT EXISTS ockam_database;
GRANT ALL ON DATABASE ockam_database TO ROLE ockam;

CREATE SCHEMA IF NOT EXISTS ockam_database.ockam_schema;
GRANT ALL ON SCHEMA ockam_database.ockam_schema TO ROLE ockam;

-- Create an image repository
CREATE IMAGE REPOSITORY IF NOT EXISTS ockam_repository;

USE ROLE ockam;

-- Create a table for logs
CREATE EVENT TABLE ockam_database.ockam_schema.ockam_events;
GRANT ALL ON EVENT TABLE ockam_database.ockam_schema.ockam_events TO ROLE ACCOUNTADMIN;

USE ROLE ACCOUNTADMIN;
ALTER ACCOUNT SET EVENT_TABLE = ockam_database.ockam_schema.ockam_events;

SHOW PARAMETERS LIKE 'event_table' IN ACCOUNT;
GRANT MODIFY LOG LEVEL ON ACCOUNT TO ROLE ockam;
