#include "ockam/vault.h"
#include "vault/default/default.h"
#include "memory/impl.h"

typedef enum {
    OCKAM_VAULT_FEATURE_RANDOM = OCKAM_VAULT_FEAT_RANDOM,
    OCKAM_VAULT_FEATURE_SHA256 = OCKAM_VAULT_FEAT_SHA256,
    OCKAM_VAULT_FEATURE_SECRET_ECDH = OCKAM_VAULT_FEAT_SECRET_ECDH,
    OCKAM_VAULT_FEATURE_HKDF_SHA256 = OCKAM_VAULT_FEAT_HKDF_SHA256,
    OCKAM_VAULT_FEATURE_AEAD_AES_GCM = OCKAM_VAULT_FEAT_AEAD_AES_GCM,
    OCKAM_VAULT_FEATURE_ALL = OCKAM_VAULT_FEAT_ALL,
} VaultFeatures;
