name: Python Cache
description: Python Cache

runs:
  using: composite
  steps:
    # We only upload cache when CI is running on a schedule (on develop)
    - uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684
      if: ${{ github.event_name == 'schedule' }}
      with:
        path: implementations/python/.venv
        key: cache-python-venv-${{ hashFiles('**/pyproject.toml') }}

    - if: ${{ github.event_name != 'schedule' }}
      uses: actions/cache/restore@5a3ec84eff668545956fd18022155c47e93e2684
      with:
        path: implementations/python/.venv
        key: cache-python-venv-${{ hashFiles('**/pyproject.toml') }}
