# System Info
set(CMAKE_SYSTEM_NAME "Linux")
set(CMAKE_SYSTEM_PROCESSOR "x86_64")
set(OCKAM_TARGET_ARCHITECTURE "x86_64")
set(OCKAM_TARGET_VENDOR "unknown")
set(OCKAM_TARGET_OS "linux")
set(OCKAM_TARGET_LIBC "gnu")
set(OCKAM_TARGET_TRIPLE
  "${OCKAM_TARGET_ARCHITECTURE}-${OCKAM_TARGET_VENDOR}-${OCKAM_TARGET_OS}-${OCKAM_TARGET_LIBC}")
