# System Info
set(CMAKE_SYSTEM_NAME "Darwin")
set(CMAKE_SYSTEM_PROCESSOR "x86_64")
set(OCKAM_TARGET_ARCHITECTURE "x86_64")
set(OCKAM_TARGET_VENDOR "apple")
set(OCKAM_TARGET_OS "darwin")
set(OCKAM_TARGET_TRIPLE "${OCKAM_TARGET_ARCHITECTURE}-${OCKAM_TARGET_VENDOR}-${OCKAM_TARGET_OS}")
