FROM ockam/builder as builder
COPY . .
WORKDIR implementations/rust
RUN cargo test --release
RUN cargo build --release --bin ockamd

FROM ubuntu:20.04
RUN apt update && apt install -y curl gnupg2
COPY --from=builder implementations/rust/target/release/ockamd /usr/local/bin/ockamd
ENTRYPOINT ["ockamd"]