# Supported target triples (case-sensitive):
#   Linux: x86_64-unknown-linux     "-DOCKAM_TARGET_PLATFORM=linux"
#   Mac: x86_64-apple-darwin        "-DOCKAM_TARGET_PLATFORM=mac"
#   Raspberry Pi: armv8-rpi3-linux  "-DOCKAM_TARGET_PLATFORM=pi"

# Set up host and target architectures (default is determined by CMAKE_HOST_SYSTEM_NAME/CMAKE_SYSTEM_NAME)
if(DEFINED OCKAM_TARGET_PLATFORM)
  if(${OCKAM_TARGET_PLATFORM} STREQUAL "pi")
    include(${CMAKE_MODULE_PATH}/platform/raspberry-pi.cmake)
    return()
  elseif(${OCKAM_TARGET_PLATFORM} STREQUAL "pi-mac")
    include(${CMAKE_MODULE_PATH}/platform/raspberry-pi-mac.cmake)
    return()
  elseif(${OCKAM_TARGET_PLATFORM} STREQUAL "mac")
    include(${CMAKE_MODULE_PATH}/platform/mac.cmake)
    return()
  elseif(${OCKAM_TARGET_PLATFORM} STREQUAL "linux")
    include(${CMAKE_MODULE_PATH}/platform/linux.cmake)
    return()
  else()
    message(FATAL_ERROR "OCKAM_TARGET_PLATFORM was specified, but is not valid. Expected one of [pi, pi-mac, mac, linux]")
  endif()
elseif(DEFINED OCKAM_TARGET_TRIPLE)
  if("${OCKAM_TARGET_TRIPLE}" MATCHES "x86_64-apple-darwin")
    include(${CMAKE_MODULE_PATH}/platform/mac.cmake)
    return()
  elseif("${OCKAM_TARGET_TRIPLE}" MATCHES "x86_64-unknown-linux")
    include(${CMAKE_MODULE_PATH}/platform/linux.cmake)
    return()
  elseif("${OCKAM_TARGET_TRIPLE}" MATCHES "armv8-rpi3-linux")
    include(${CMAKE_MODULE_PATH}/platform/raspberry-pi.cmake)
    return()
  else()
    message(FATAL_ERROR "OCKAM_TARGET_TRIPLE was specified, but the specified target is not recognized.")
  endif()
else()
  if("${CMAKE_SYSTEM_PROCESSOR}" STREQUAL "x86_64")
    if("${CMAKE_SYSTEM_NAME}" STREQUAL "Linux")
      include(${CMAKE_MODULE_PATH}/platform/linux.cmake)
      return()
    elseif("${CMAKE_SYSTEM_NAME}" MATCHES "([dD]arwin|Mac OS X)")
      include(${CMAKE_MODULE_PATH}/platform/mac.cmake)
    endif()
  elseif("${CMAKE_SYSTEM_PROCESSOR}" STREQUAL "armv8")
    if("${CMAKE_SYSTEM_NAME}" STREQUAL "Linux")
      message(WARNING "Falling back to detecting target platform. It is recommended to specify OCKAM_TARGET_PLATFORM or OCKAM_TARGET_TRIPLE")
      message(WARNING "Detected target arch/os is armv8/linux, assuming target triple of armv8-rpi3-linux-gnueabihf")
      if("${CMAKE_HOST_SYSTEM_NAME}" STREQUAL "Darwin")
        include(${CMAKE_MODULE_PATH}/platform/raspberry-pi-mac.cmake)
        return()
      else()
        include(${CMAKE_MODULE_PATH}/platform/raspberry-pi.cmake)
        return()
      endif()
    endif()
  endif()
endif()

message(FATAL_ERROR "Unable to determine target platform!")
