#!/bin/bash

# This scripts deploys a stress test client and an ockam client to a remote machine accessible via ssh.

set -e

cd "$(dirname "$0")"/../../

if [ "$#" -lt 1 ]; then
    echo "usage: $0 <[username@]host>"
    exit 1
fi

export SSH_ENDPOINT="$1"

function ssh {
    /usr/bin/env ssh -q -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o LogLevel=QUIET -o ConnectTimeout=5 "${SSH_ENDPOINT}" "$@"
}

function scp {
    /usr/bin/env scp -q -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o LogLevel=QUIET -o ConnectTimeout=5 "$@"
}

TARGET_ARCHITECTURE=$(ssh uname -m)

# always use cross-compilation to avoid reliance on new and unsupported glibc versions
cross build --bin=stress-test --bin=ockam -F aws-lc --release --target "${TARGET_ARCHITECTURE}-unknown-linux-gnu"
echo "uploading..."

scp \
  "target/${TARGET_ARCHITECTURE}-unknown-linux-gnu/release/stress-test" \
  "target/${TARGET_ARCHITECTURE}-unknown-linux-gnu/release/ockam" \
  "${SSH_ENDPOINT}:"

ssh sudo mv ockam stress-test /usr/local/bin/
ssh ockam identity create admin
