pub const ERROR_INTERFACE_MASK: u32 = 0xFF000000;
pub const ERROR_INTERFACE_SHIFT: u32 = 24u32;
pub const ERROR_NONE: u32 = 0u32;

pub const ERROR_INTERFACE_MEMORY: u32 = (1u32 << ERROR_INTERFACE_SHIFT);
pub const ERROR_INTERFACE_LOG: u32 = (2u32 << ERROR_INTERFACE_SHIFT);
pub const ERROR_INTERFACE_VAULT: u32 = (3u32 << ERROR_INTERFACE_SHIFT);
pub const ERROR_INTERFACE_TRANSPORT: u32 = (4u32 << ERROR_INTERFACE_SHIFT);
pub const ERROR_INTERFACE_KEYAGREEMENT: u32 = (5u32 << ERROR_INTERFACE_SHIFT);
pub const ERROR_INTERFACE_RANDOM: u32 = (6u32 << ERROR_INTERFACE_SHIFT);
pub const ERROR_INTERFACE_IO: u32 = (7u32 << ERROR_INTERFACE_SHIFT);
pub const ERROR_INTERFACE_CHANNEL: u32 = (8u32 << ERROR_INTERFACE_SHIFT);
pub const ERROR_INTERFACE_ROUTER: u32 = (9u32 << ERROR_INTERFACE_SHIFT);
pub const ERROR_INTERFACE_CODEC: u32 = (10u32 << ERROR_INTERFACE_SHIFT);
pub const ERROR_INTERFACE_QUEUE: u32 = (11u32 << ERROR_INTERFACE_SHIFT);

pub type OckamResult<T> = Result<T, u32>;
