sequenceDiagram
  participant app
  participant channel_initiator
  participant hop1
  participant hop2
  participant hop3
  participant channel_responder
  participant channel_listener
  participant echoer

  rect rgba(0, 0, 255, .1)
    Note right of channel_initiator: Secure Channel Setup
    channel_initiator->>+channel_listener: Handshake M1
    channel_listener-->>+channel_responder: Handshake M1
    channel_responder->>+channel_initiator: Handshake M2
    channel_initiator->>+channel_responder: Handshake M3
  end

  app->>+channel_initiator: Hello Ockam!
  channel_initiator->>+channel_responder: Encrypted("Hello Ockam!")
  channel_responder->>+echoer: Hello Ockam!
  echoer->>-channel_responder: Hello Ockam!
  channel_responder->>-channel_initiator: Encrypted("Hello Ockam!")
  channel_initiator->>-app: Hello Ockam!
