name: Ockam Python Image Release

permissions:
  contents: read

on:
  push:
    paths:
    - ".github/workflows/release-python-image.yml"
    - "implementations/python/**"
    branches:
    - develop
  workflow_dispatch:
    inputs:
      commit_sha:
        description: Commit SHA to build Ockam AI Image
        required: true
      is_latest:
        description: Build as latest image
        default: false
        type: boolean

jobs:
  build_as_sha:
    name: Build Ockam AI Image as Tagged SHA
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - name: login to GitHub Container Registry
      uses: docker/login-action@6d4b68b490aef8836e8fb5e50ee7b3bdfa5894f0
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Checkout Ockam Repository
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      with:
        ref: ${{ github.event.inputs.commit_sha == '' && github.sha || github.event.inputs.commit_sha }}

    - name: Build Ockam AI Image
      run: |
        # Get SHA and check if image is pushed to registry, exit if it is.
        current_sha="${{ github.event.inputs.commit_sha == '' && github.sha || github.event.inputs.commit_sha }}"
        echo "Current SHA: $current_sha"
        docker pull ghcr.io/build-trust/ockam-python:$current_sha && exit 0 || true

        cd implementations/python
        make build-image-amd64
        make release-image-amd64-hash

  build_as_latest:
    name: Build Ockam AI Image as Latest
    runs-on: ubuntu-latest
    needs: build_as_sha
    permissions:
      contents: read
      packages: write
    if: ${{ github.event.inputs.is_latest == 'true' }}
    steps:
    - name: login to GitHub Container Registry
      uses: docker/login-action@6d4b68b490aef8836e8fb5e50ee7b3bdfa5894f0
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Checkout Ockam Repository
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      with:
        ref: ${{ github.event.inputs.commit_sha == '' && github.sha || github.event.inputs.commit_sha }}

    - name: Build Ockam AI Image as Latest
      run: |
        current_sha="${{ github.event.inputs.commit_sha == '' && github.sha || github.event.inputs.commit_sha }}"
        echo "Current SHA: $current_sha"

        docker pull "ghcr.io/build-trust/ockam-python:$current_sha"
        docker pull "ghcr.io/build-trust/ockam-python-dev:$current_sha"

        make -f implementations/python/Makefile release-image-amd64-latest
