name: OSSF Scorecards

permissions:
  contents: read

on:
  branch_protection_rule:
  push:
    branches:
      - develop
  schedule:
    # At 1am on Monday
    - cron: '0 1 * * 1'

jobs:
  analyze:
    name: OSSF Scorecards - analyze
    runs-on: ubuntu-22.04
    permissions:
      actions: read
      contents: read
      security-events: write # Needed to upload results to code-scanning dashboard.
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        with:
          persist-credentials: false

      - name: Analyze
        uses: ossf/scorecard-action@f49aabe0b5af0936a0987cfb85d86b75731b0186
        with:
          results_file: results.sarif
          results_format: sarif
          repo_token: ${{ secrets.SCORECARD_READ_TOKEN }}
          publish_results: true

      - name: "Upload to code-scanning"
        uses: github/codeql-action/upload-sarif@fc7e4a0fa01c3cca5fd6a1fddec5c0740c977aa2
        with:
          sarif_file: results.sarif
