name: Typos
on: pull_request

permissions:
  contents: read

jobs:
  run:
    name: Spell check with Typos
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Actions Repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

      - name: Check spelling
        uses: crate-ci/typos@a9ccf76b53d1ace194871d216f9ff058599a86db
        with:
          config: tools/typos/typos.toml
