USE ROLE ACCOUNTADMIN;
USE DATABASE MSSQL_CONNECTOR_DB;
USE SCHEMA MSSQL_CONNECTOR_SCHEMA;

!set variable_substitution=true
!variables

-- Update VALUE_LIST with ockam egress details
CREATE OR REPLACE NETWORK RULE OCKAM_OUT
    TYPE = 'HOST_PORT'
    MODE = 'EGRESS'
    VALUE_LIST = ('&egress_list');

CREATE OR REPLACE EXTERNAL ACCESS INTEGRATION OCKAM
    ALLOWED_NETWORK_RULES = (OCKAM_OUT)
    ENABLED = true;

GRANT USAGE ON INTEGRATION OCKAM TO ROLE MSSQL_CONNECTOR_ROLE;

--- Describe the network rule to verify it was created correctly
DESCRIBE NETWORK RULE OCKAM_OUT;


USE ROLE MSSQL_CONNECTOR_ROLE;
USE DATABASE MSSQL_CONNECTOR_DB;
USE WAREHOUSE MSSQL_CONNECTOR_WH;
USE SCHEMA MSSQL_CONNECTOR_SCHEMA;


CREATE OR REPLACE NETWORK RULE OCSP_OUT
TYPE = 'HOST_PORT' MODE= 'EGRESS'
VALUE_LIST = ('ocsp.snowflakecomputing.com:80');

-- Create access integration

USE ROLE ACCOUNTADMIN;

GRANT CREATE INTEGRATION ON ACCOUNT TO ROLE MSSQL_CONNECTOR_ROLE;

CREATE OR REPLACE EXTERNAL ACCESS INTEGRATION OCSP
ALLOWED_NETWORK_RULES = (OCSP_OUT)
ENABLED = true;

GRANT USAGE ON INTEGRATION OCSP TO ROLE MSSQL_CONNECTOR_ROLE;


