-- Switch to ACCOUNTADMIN role for full cleanup permissions
USE ROLE ACCOUNTADMIN;
USE DATABASE MSSQL_CONNECTOR_DB;
USE SCHEMA MSSQL_CONNECTOR_SCHEMA;

-- Drop Stored Procedures and Functions
DROP PROCEDURE IF EXISTS ockam_mssql_copy(STRING, STRING);
DROP FUNCTION IF EXISTS _ockam_copy_from_mssql(STRING, STRING);

-- Drop Service
DROP SERVICE IF EXISTS MSSQL_CONNECTOR_CLIENT;

-- Drop External Access Integrations
DROP INTEGRATION IF EXISTS OCKAM;
DROP INTEGRATION IF EXISTS OCSP;

-- Drop Network Rules
DROP NETWORK RULE IF EXISTS OCKAM_OUT;
DROP NETWORK RULE IF EXISTS OCSP_OUT;

-- Drop Image Repository
DROP IMAGE REPOSITORY IF EXISTS MSSQL_CONNECTOR_REPOSITORY;

-- Drop Schema
DROP SCHEMA IF EXISTS MSSQL_CONNECTOR_SCHEMA;

-- Drop Compute Pool
DROP COMPUTE POOL IF EXISTS MSSQL_CONNECTOR_CP;

-- Drop Warehouse
DROP WAREHOUSE IF EXISTS MSSQL_CONNECTOR_WH;

-- Drop Database
DROP DATABASE IF EXISTS MSSQL_CONNECTOR_DB;

-- Drop Role
DROP ROLE IF EXISTS MSSQL_CONNECTOR_ROLE;
